filters:
  comments: 'true'
plugins:
  '@textlint/markdown':
    extensions:
      - .md
rules:
  '@textlint-ja/no-synonyms': true
  '@textlint-ja/textlint-rule-no-dropping-i': true
  '@textlint-ja/textlint-rule-no-insert-dropping-sa': true
  abbr-within-parentheses: true
  footnote-order: true
  general-novel-style-ja:
    appropriate_use_of_choonpu: true
    appropriate_use_of_interpunct: true
    appropriate_use_of_minus_sign: true
    appropriate_use_of_punctuation: true
    chars_leading_paragraph: false
    even_number_dashes: true
    even_number_ellipsises: true
    max_arabic_numeral_digits: false
    no_punctuation_at_closing_quote: false
    space_after_marks: false
  ja-hiragana-fukushi: true
  ja-hiragana-hojodoushi: true
  ja-hiragana-keishikimeishi: true
  no-mixed-zenkaku-and-hankaku-alphabet: true
  period-in-list-item:
    allowEmoji: false
    allowPeriodMarks: []
    forceAppendPeriod: false
    ignoreLinkEnd: true
    periodMark: ''
    periodMarks:
      - .
      - 。
      - ．
  prefer-tari-tari: true
  preset-ja-spacing:
    ja-nakaguro-or-halfwidth-space-between-katakana: true
    ja-no-space-around-parentheses: true
    ja-no-space-between-full-width: true
    ja-space-after-exclamation: false
    ja-space-after-question: false
    ja-space-around-code:
      after: 'true'
      before: 'true'
    ja-space-between-half-and-full-width:
      space: never
  preset-ja-technical-writing:
    arabic-kanji-numbers: true
    ja-no-abusage: true
    ja-no-mixed-period:
      allowPeriodMarks:
        - ':'
        - ：
    ja-no-redundant-expression:
      severity: warning
    ja-no-successive-word: true
    ja-no-weak-phrase:
      severity: warning
    ja-unnatural-alphabet:
      allow:
        - /[A-Z]/
      allowCommonCase: true
    max-comma:
      max: 3
    max-kanji-continuous-len:
      max: 6
    max-ten:
      max: 3
    no-doubled-joshi:
      allow:
        - も
        - や
        - か
      min_interval: 1
      separatorCharacters:
        - ','
        - ，
        - 、
        - .
        - ．
        - 。
        - '?'
        - '!'
        - ？
        - ！
        - 「
        - 」
        - '"'
        - ”
        - “
      severity: warning
      strict: 'false'
    no-dropping-the-ra: true
    no-exclamation-question-mark:
      allowFullWidthExclamation: 'true'
      allowFullWidthQuestion: 'true'
    no-hankaku-kana: true
    no-invalid-control-character: false
    no-mix-dearu-desumasu:
      preferInBody: ですます
      preferInHeader: ''
      preferInList: である
      strict: false
    no-nfd: true
    no-unmatched-pair: true
    sentence-length:
      max: '150'
      severity: warning
  preset-jtf-style:
    1.1.1.本文: true
    1.1.2.見出し: true
    1.1.3.箇条書き: true
    1.1.5.図表のキャプション: true
    1.2.1.句点(。)と読点(、): true
    1.2.2.ピリオド(.)とカンマ(,): true
    2.1.10.算用数字の位取りの表記: true
    2.1.2.漢字: false
    2.1.5.カタカナ: false
    2.1.6.カタカナの長音: false
    2.1.8.算用数字: true
    2.1.9.アルファベット: true
    2.2.1.ひらがなと漢字の使い分け: false
    2.2.2.算用数字と漢数字の使い分け: true
    2.2.3.一部の助数詞の表記: true
    3.1.1.全角文字と半角文字の間: true
    3.1.2.全角文字どうし: true
    3.2.カタカナ語間のスペースの有無: true
    3.3.かっこ類と隣接する文字の間のスペースの有無: true
    4.1.1.句点(。): true
    4.1.3.ピリオド(.)、カンマ(,): true
    4.2.1.感嘆符(！): true
    4.2.2.疑問符(？): true
    4.2.4.中黒(・): true
    4.2.5.波線(〜): true
    4.2.6.ハイフン(-): true
    4.2.7.コロン(:): true
    4.2.8.セミコロン(;): true
    4.2.9.ダッシュ(-): true
    4.3.1.丸かっこ（）: true
    4.3.2.大かっこ[]: true
    4.3.3.かぎかっこ「」: true
    4.3.4.二重かぎかっこ『』: true
    4.3.5.二重引用符: true
    4.3.6.中かっこ{ }: true
    4.3.7.山かっこ<>: true
    4.3.8.一重引用符: true
  prh:
    rulePaths:
      - ./prh/index.yml
  textlint-rule-date-weekday-mismatch: true
  textlint-rule-ja-no-inappropriate-words: true
  textlint-rule-ja-no-orthographic-variants: true
  textlint-rule-no-hoso-kinshi-yogo: true
  textlint-rule-use-si-units: true
  textlint-rule-write-good: true
