name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Build
      id: build
      run: |
        pnpm install --frozen-lockfile
        pnpm lint
